# Generated by Django 5.2.5 on 2025-08-10 23:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assignments', '0001_initial'),
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.IntegerField(help_text='Total number of tasks in this homework', validators=[django.core.validators.MinValueValidator(0)])),
                ('solved_tasks', models.IntegerField(help_text='Number of tasks completed by the student', validators=[django.core.validators.MinValueValidator(0)])),
                ('is_completed', models.BooleanField(default=False, help_text='Whether the homework is fully completed')),
                ('last_attempt_at', models.DateTimeField(help_text='When the student last worked on this homework')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='assignments.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_progress', to='accounts.student')),
            ],
            options={
                'verbose_name': 'Homework Progress',
                'verbose_name_plural': 'Homework Progress',
                'db_table': 'progress_homework_progress',
                'ordering': ['-last_attempt_at'],
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_solved', models.BooleanField(default=False, help_text='Whether the task is completed successfully')),
                ('best_passed_tests', models.IntegerField(default=0, help_text='Highest number of test cases passed', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tests', models.IntegerField(help_text='Total number of test cases for this task', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_attempt_at', models.DateTimeField(help_text='When the student last attempted this task')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_submission', models.ForeignKey(blank=True, help_text='Reference to the most recent submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='submissions.homeworksubmission')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_progress', to='accounts.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='assignments.task')),
            ],
            options={
                'verbose_name': 'Task Progress',
                'verbose_name_plural': 'Task Progress',
                'db_table': 'progress_task_progress',
                'ordering': ['-last_attempt_at'],
                'unique_together': {('task', 'student')},
            },
        ),
    ]
