# Generated by Django 5.2.5 on 2025-09-16 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='homework_progress',
            field=models.ForeignKey(blank=True, help_text='Reference to the parent HomeworkProgress record (nullable for migration)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_progresses', to='progress.homeworkprogress'),
        ),
    ]
