# Generated by Django 5.2.5 on 2025-09-15 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_student_groups'),
        ('courses', '0002_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='current_lesson',
            field=models.ForeignKey(blank=True, help_text='The lesson currently being taught in this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_groups', to='courses.lessons'),
        ),
        migrations.AddField(
            model_name='group',
            name='last_taught_date',
            field=models.DateTimeField(blank=True, help_text='When the current lesson was last taught', null=True),
        ),
    ]
