# Generated by Django 5.2.5 on 2025-09-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_group_current_lesson_group_last_taught_date'),
        ('courses', '0003_alter_lessons_options_lessons_order_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='current_course',
            field=models.ForeignKey(blank=True, help_text='The course currently being taught in this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_groups', to='courses.course'),
        ),
    ]
