# Generated by Django 5.2.5 on 2025-09-24 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_group_current_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week for this recurring lesson', max_length=10)),
                ('start_time', models.TimeField(help_text='Start time of the lesson')),
                ('end_time', models.TimeField(help_text='End time of the lesson')),
                ('start_date', models.DateField(help_text='Start date of the recurring schedule')),
                ('end_date', models.DateField(blank=True, help_text='Optional manual override for end date (leave blank to use course duration)', null=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='True for weekly recurring schedules')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this schedule is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='Group being taught in this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.group')),
                ('teacher', models.ForeignKey(help_text='Teacher assigned to this schedule', on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'accounts_schedule',
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('group', 'teacher', 'day_of_week', 'start_time')},
            },
        ),
    ]
