# Generated by Django 5.2.5 on 2025-09-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes for admin use only - not visible to students', null=True),
        ),
    ]
