# Generated by Django 5.2.5 on 2025-08-10 23:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_text', models.TextField(help_text='The submitted code as text')),
                ('file_upload', models.FileField(blank=True, help_text='Optional file upload for the submission', null=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, help_text='When this submission was made')),
                ('passed_tests', models.IntegerField(default=0, help_text='Number of test cases passed by this submission', validators=[django.core.validators.MinValueValidator(0)])),
                ('total_tests', models.IntegerField(help_text='Total number of test cases for this task', validators=[django.core.validators.MinValueValidator(0)])),
                ('execution_time', models.FloatField(blank=True, help_text='Execution time in seconds (if measured)', null=True)),
                ('memory_usage', models.IntegerField(blank=True, help_text='Memory usage in KB (if measured)', null=True)),
                ('student', models.ForeignKey(help_text='The student who made this submission', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.student')),
                ('task', models.ForeignKey(help_text='The task this submission is for', on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.task')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'db_table': 'submissions_homework_submission',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['task', 'student'], name='submissions_task_id_304a84_idx'), models.Index(fields=['submitted_at'], name='submissions_submitt_bb2d55_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.TextField(help_text='The test code to execute for validation')),
                ('hidden', models.BooleanField(default=False, help_text='Whether this test case is hidden from students')),
                ('input_data', models.TextField(blank=True, help_text='Input data for the test case')),
                ('expected_output', models.TextField(blank=True, help_text='Expected output for the test case')),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Maximum execution time allowed for this test', validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(help_text='The task this test case belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='assignments.task')),
            ],
            options={
                'verbose_name': 'Test Case',
                'verbose_name_plural': 'Test Cases',
                'db_table': 'submissions_test_case',
                'ordering': ['task', 'hidden', 'created_at'],
                'indexes': [models.Index(fields=['task', 'hidden'], name='submissions_task_id_1dc566_idx')],
            },
        ),
    ]
