# Generated by Django 5.2.5 on 2025-08-29 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_group_student_groups'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=10)),
                ('date', models.DateField(help_text='Date of the lesson')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about attendance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(help_text='Group in which the lesson was conducted', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.group')),
                ('lesson', models.ForeignKey(help_text='Lesson for which attendance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='courses.lessons')),
                ('student', models.ForeignKey(help_text='Student whose attendance is being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student')),
                ('teacher', models.ForeignKey(help_text='Teacher who recorded the attendance', on_delete=django.db.models.deletion.CASCADE, related_name='recorded_attendances', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'courses_attendance',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'lesson', 'group', 'date')},
            },
        ),
    ]
