# Generated by Django 5.2.5 on 2025-09-15 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_group_current_lesson_group_last_taught_date'),
        ('courses', '0002_attendance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lessons',
            options={'ordering': ['course', 'order'], 'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AddField(
            model_name='lessons',
            name='order',
            field=models.PositiveIntegerField(default=1, help_text='Order of this lesson within the course'),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField(help_text='Course duration in weeks')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this course is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teachers', models.ManyToManyField(blank=True, help_text='Teachers who can teach this course', related_name='courses', to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses_course',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='lessons',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Course this lesson belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
        ),
    ]
