# Generated by Django 5.2.5 on 2025-09-17 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_group_current_course'),
        ('courses', '0003_alter_lessons_options_lessons_order_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount due for this month', max_digits=10)),
                ('due_date', models.DateField(help_text='Date when payment is due')),
                ('paid_date', models.DateTimeField(blank=True, help_text='Date and time when payment was made', null=True)),
                ('month', models.PositiveIntegerField(help_text='Month for which payment is due (1-12)')),
                ('year', models.PositiveIntegerField(help_text='Year for which payment is due')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the payment', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('payment_method', models.CharField(blank=True, help_text='Method used for payment (cash, card, transfer, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, help_text='The course for which this payment is due (optional, derived from group)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course')),
                ('group', models.ForeignKey(help_text='The group for which this payment is due', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='accounts.group')),
                ('processed_by', models.ForeignKey(blank=True, help_text='Admin user who processed this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='The student who needs to make this payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'admin_panel_payment',
                'ordering': ['-year', '-month', 'due_date', 'student__first_name'],
                'indexes': [models.Index(fields=['status', 'due_date'], name='admin_panel_status_355f5d_idx'), models.Index(fields=['month', 'year'], name='admin_panel_month_cd008d_idx'), models.Index(fields=['student', 'status'], name='admin_panel_student_2982e7_idx')],
                'unique_together': {('student', 'group', 'month', 'year')},
            },
        ),
    ]
