# Generated by Django 5.2.5 on 2025-09-17 10:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount that has been paid so far', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount due for this month', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateTimeField(blank=True, help_text='Date and time when payment was fully paid', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the payment', max_length=15),
        ),
        migrations.CreateModel(
            name='StudentPaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('warning', 'Payment Warning'), ('suspended', 'Suspended for Non-Payment'), ('expelled', 'Expelled')], default='active', help_text='Current payment status of the student', max_length=20)),
                ('consecutive_unpaid_months', models.PositiveIntegerField(default=0, help_text='Number of consecutive months without payment')),
                ('total_debt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount owed across all unpaid payments', max_digits=10)),
                ('last_payment_date', models.DateField(blank=True, help_text='Date of last payment made', null=True)),
                ('suspension_date', models.DateField(blank=True, help_text='Date when student was suspended', null=True)),
                ('warning_sent_date', models.DateField(blank=True, help_text='Date when last warning was sent', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about payment status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(help_text='Student user account', on_delete=django.db.models.deletion.CASCADE, related_name='payment_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Payment Status',
                'verbose_name_plural': 'Student Payment Statuses',
                'db_table': 'admin_panel_student_payment_status',
                'ordering': ['-consecutive_unpaid_months', '-total_debt'],
            },
        ),
    ]
