# Generated by Django 5.2.5 on 2025-10-04 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_student_admin_notes'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message content')),
                ('notification_type', models.CharField(choices=[('assignment', 'New Assignment'), ('submission', 'Submission Graded'), ('progress', 'Progress Milestone'), ('schedule', 'Schedule Change'), ('announcement', 'General Announcement'), ('deadline', 'Deadline Reminder'), ('payment', 'Payment Notification'), ('student_payment', 'Student Payment Status'), ('teacher_payment', 'Teacher Payment')], help_text='Type of notification', max_length=20)),
                ('recipient_role', models.CharField(choices=[('admin', 'Admin Only'), ('teacher', 'Teachers Only'), ('student', 'Students Only'), ('all', 'All Users')], default='all', help_text='Target role for this notification', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Notification priority level', max_length=10)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, help_text='Whether notification has been read')),
                ('is_sent', models.BooleanField(default=False, help_text='Whether notification has been sent')),
                ('read_at', models.DateTimeField(blank=True, help_text='When notification was read', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(blank=True, help_text='Specific recipient (optional, for targeted notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications_notification',
                'ordering': ['-created_at', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, help_text='Receive notifications via email')),
                ('push_notifications', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('assignment_notifications', models.BooleanField(default=True, help_text='Receive assignment-related notifications')),
                ('submission_notifications', models.BooleanField(default=True, help_text='Receive submission-related notifications')),
                ('progress_notifications', models.BooleanField(default=True, help_text='Receive progress-related notifications')),
                ('schedule_notifications', models.BooleanField(default=True, help_text='Receive schedule-related notifications')),
                ('payment_notifications', models.BooleanField(default=True, help_text='Receive payment-related notifications (admin only)')),
                ('student_payment_notifications', models.BooleanField(default=True, help_text='Receive student payment notifications (admin only)')),
                ('teacher_payment_notifications', models.BooleanField(default=True, help_text='Receive teacher payment notifications (admin only)')),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly')], default='immediate', help_text='How often to receive notification digests', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notifications_preference',
            },
        ),
        migrations.CreateModel(
            name='PaymentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('tuition', 'Tuition Payment'), ('salary', 'Teacher Salary'), ('refund', 'Refund'), ('penalty', 'Late Payment Penalty'), ('bonus', 'Bonus Payment')], help_text='Type of payment', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], help_text='Status of the payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Payment currency', max_length=3)),
                ('payment_reference', models.CharField(help_text='Unique payment reference', max_length=100, unique=True)),
                ('due_date', models.DateTimeField(blank=True, help_text='Payment due date', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_details', to='notifications.notification')),
                ('student', models.ForeignKey(blank=True, help_text='Student related to this payment (for tuition)', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
                ('teacher', models.ForeignKey(blank=True, help_text='Teacher related to this payment (for salary)', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.teacher')),
            ],
            options={
                'verbose_name': 'Payment Notification',
                'verbose_name_plural': 'Payment Notifications',
                'db_table': 'notifications_payment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'recipient_role'], name='notificatio_notific_bef835_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
    ]
